// Auto-generated by ArchiveDLGui
// name = عنوان ویدیو | link = مسیر فایل
const videoList = [
  {
    "name": "Sita Sings the Blues",
    "link": "video/Sita Sings the Blues [480p].mp4"
  }
];
